# Generated by Django 2.0.7 on 2018-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=32)),
                ('connect', models.CharField(default='connect', max_length=64)),
                ('page', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
